version: '3'
services:
  app:
    build:
      context: .
      args:
        BUILD_MODE: dev
    image: inventory-manager-django-dev
    container_name: inventory-manager-dev
    user: "${UID}:${GID}"
    ports:
      - 8001:8000
    volumes:
      - ./:/app
    env_file:
      - dev.env
