# Generated by Django 4.1.5 on 2023-03-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Planogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inline', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('home_locations', models.ManyToManyField(related_name='products', to='product_locator.homelocation')),
            ],
        ),
        migrations.AddField(
            model_name='homelocation',
            name='planogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='product_locator.planogram'),
        ),
    ]
