# Generated by Django 4.1.5 on 2023-03-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
