# Generated by Django 4.0.1 on 2023-08-09 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('product_locator', '0002_planogram_date_end_planogram_date_start_and_more'), ('product_locator', '0003_alter_planogram_date_end')]

    dependencies = [
        ('product_locator', '0001_initial_squashed_0006_store_alter_planogram_name_planogram_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planogram',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='home_locations',
            field=models.ManyToManyField(related_name='products', to='product_locator.HomeLocation'),
        ),
        migrations.AddField(
            model_name='planogram',
            name='date_end',
            field=models.DateField(null=True, blank=True),
        ),
    ]
