# Generated by Django 4.0.1 on 2023-08-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0002_planogram_date_end_planogram_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planogram',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
