# Generated by Django 4.0.1 on 2023-08-23 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0002_planogram_date_end_planogram_date_start_and_more_squashed_0003_alter_planogram_date_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScanAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('products_in_stock', models.ManyToManyField(related_name='scan_audits', to='product_locator.Product')),
            ],
        ),
    ]
