# Generated by Django 4.1.5 on 2023-03-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homelocation',
            old_name='location',
            new_name='name',
        ),
    ]
