# Generated by Django 4.1.5 on 2023-03-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0003_rename_location_homelocation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planogram',
            name='name',
            field=models.CharField(default='Inline', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='homelocation',
            unique_together={('name', 'planogram')},
        ),
    ]
