# Generated by Django 4.0.1 on 2023-08-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0003_productscanaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscanaudit',
            name='product_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
