# Generated by Django 4.1.5 on 2023-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0004_alter_planogram_name_alter_product_upc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planogram',
            name='name',
            field=models.CharField(default='Inline Plano', max_length=50, unique=True),
        ),
    ]
