# Generated by Django 4.0.1 on 2025-11-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0004_productscanaudit_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='planogram',
            name='plano_type',
            field=models.CharField(choices=[('regular', 'Regular Planogram'), ('seasonal', 'Seasonal Planogram'), ('other', 'Other Planogram')], default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
