# Generated by Django 4.0.1 on 2026-07-17 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0005_planogram_plano_type_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanogramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('old_plano', models.JSONField()),
                ('new_plano', models.JSONField()),
                ('planogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planogram_updates', to='product_locator.planogram')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
