# Generated by Django 4.0.1 on 2026-07-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0006_planogramupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='planogramupdate',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
