# Generated by Django 5.2.16 on 2026-09-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0007_planogramupdate_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='planogram',
            name='horizontal_section_thresholds',
            field=models.JSONField(default=list),
        ),
    ]
