# Generated by Django 5.2.16 on 2026-09-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_locator', '0008_planogram_horizontal_section_thresholds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planogram',
            name='horizontal_section_thresholds',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
