# Generated by Django 4.1.5 on 2023-02-20 03:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial'), ('products', '0002_rename_personnelcontact_storecontact'), ('products', '0003_remove_store_personnel_contact_and_more'), ('products', '0004_storeproductdata'), ('products', '0005_contactinfo'), ('products', '0006_rename_contactinfo_personnelcontact_and_more'), ('products', '0007_alter_personnelcontact_first_name_and_more'), ('products', '0008_alter_storeproductdata_store'), ('products', '0009_alter_storeproductdata_product_and_more'), ('products', '0010_rename_storeproductdata_productadditions'), ('products', '0011_rename_productadditions_productaddition'), ('products', '0012_alter_productaddition_added_date'), ('products', '0013_alter_productaddition_unique_together'), ('products', '0014_alter_store_store_contact'), ('products', '0015_alter_productaddition_is_carried'), ('products', '0016_workcycle'), ('products', '0017_fieldrepresentative_store_field_representative'), ('products', '0018_alter_store_field_representative'), ('products', '0019_alter_fieldrepresentative_work_email_and_more'), ('products', '0020_product_parent_company'), ('products', '0021_brandparentcompany_alter_product_parent_company'), ('products', '0022_alter_brandparentcompany_name'), ('products', '0023_rename_name_brandparentcompany_short_name_and_more'), ('products', '0024_alter_brandparentcompany_expanded_name'), ('products', '0025_alter_product_name'), ('products', '0026_alter_store_store_contact'), ('products', '0027_rename_added_date_productaddition_date_added'), ('products', '0028_alter_store_store_contact'), ('products', '0029_alter_store_field_representative'), ('products', '0030_alter_product_parent_company'), ('products', '0031_productaddition_date_last_scanned'), ('products', '0032_alter_personnelcontact_first_name_and_more'), ('products', '0033_alter_productaddition_date_last_scanned'), ('products', '0034_alter_productaddition_date_added_and_more'), ('products', '0035_alter_product_parent_company'), ('products', '0036_alter_product_parent_company'), ('products', '0037_alter_product_parent_company'), ('products', '0038_alter_product_parent_company'), ('products', '0039_alter_brandparentcompany_expanded_name'), ('products', '0040_alter_brandparentcompany_short_name'), ('products', '0041_remove_store_store_contact_personnelcontact_store'), ('products', '0042_alter_brandparentcompany_short_name'), ('products', '0043_alter_brandparentcompany_table_and_more'), ('products', '0044_product_item_image'), ('products', '0045_alter_product_item_image'), ('products', '0046_alter_product_item_image')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandParentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('expanded_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upcs', to='products.brandparentcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('field_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='products.fieldrepresentative')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('is_carried', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_additions', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_additions', to='products.store')),
                ('date_last_scanned', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('store', 'product')},
            },
        ),
        migrations.CreateModel(
            name='WorkCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='products.store')),
            ],
        ),
        migrations.AlterModelTable(
            name='brandparentcompany',
            table='brand_parent_companies',
        ),
        migrations.AlterModelTable(
            name='fieldrepresentative',
            table='field_representatives',
        ),
        migrations.AlterModelTable(
            name='personnelcontact',
            table='personnel_contacts',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productaddition',
            table='product_additions',
        ),
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
        migrations.AlterModelTable(
            name='workcycle',
            table='work_cycles',
        ),
        migrations.AddField(
            model_name='product',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_upload_location),
        ),
    ]
