# Generated by Django 4.1.5 on 2023-01-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonnelContact',
            new_name='StoreContact',
        ),
    ]
