# Generated by Django 4.1.5 on 2023-01-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_personnelcontact_storecontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='personnel_contact',
        ),
        migrations.RemoveField(
            model_name='store',
            name='products_carried',
        ),
        migrations.RemoveField(
            model_name='store',
            name='products_surveyed',
        ),
        migrations.AddField(
            model_name='store',
            name='contact_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='StoreContact',
        ),
    ]
