# Generated by Django 4.1.5 on 2023-01-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_storeproductdata_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductdata',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_additions', to='products.product'),
        ),
        migrations.AlterField(
            model_name='storeproductdata',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_additions', to='products.store'),
        ),
    ]
