# Generated by Django 4.1.5 on 2023-01-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_storeproductdata_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreProductData',
            new_name='ProductAdditions',
        ),
    ]
