# Generated by Django 4.1.5 on 2023-01-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_storeproductdata_productadditions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAdditions',
            new_name='ProductAddition',
        ),
    ]
