# Generated by Django 4.1.5 on 2023-01-06 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_productadditions_productaddition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaddition',
            name='added_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
