# Generated by Django 4.1.5 on 2023-01-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productaddition_added_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productaddition',
            unique_together={('store', 'product')},
        ),
    ]
