# Generated by Django 4.1.5 on 2023-01-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_store_store_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaddition',
            name='is_carried',
            field=models.BooleanField(default=False),
        ),
    ]
