# Generated by Django 4.1.5 on 2023-01-06 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_workcycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='field_representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stores', to='products.fieldrepresentative'),
        ),
    ]
