# Generated by Django 4.1.5 on 2023-01-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_fieldrepresentative_store_field_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='field_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stores', to='products.fieldrepresentative'),
        ),
    ]
