# Generated by Django 4.1.5 on 2023-01-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_store_field_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldrepresentative',
            name='work_email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
