# Generated by Django 4.1.5 on 2023-01-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_brandparentcompany_alter_product_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandparentcompany',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
