# Generated by Django 4.1.5 on 2023-01-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_brandparentcompany_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandparentcompany',
            old_name='name',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='brandparentcompany',
            name='expanded_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
