# Generated by Django 4.1.5 on 2023-01-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_rename_name_brandparentcompany_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandparentcompany',
            name='expanded_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
