# Generated by Django 4.1.5 on 2023-01-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_store_store_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaddition',
            old_name='added_date',
            new_name='date_added',
        ),
    ]
