# Generated by Django 4.1.5 on 2023-01-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_rename_added_date_productaddition_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_stores', to='products.personnelcontact'),
        ),
    ]
