# Generated by Django 4.1.5 on 2023-01-16 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_store_store_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='field_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='products.fieldrepresentative'),
        ),
    ]
