# Generated by Django 4.1.5 on 2023-01-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_parent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaddition',
            name='date_last_scanned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
