# Generated by Django 4.1.5 on 2023-01-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_productaddition_date_last_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelcontact',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personnelcontact',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
