# Generated by Django 4.1.5 on 2023-01-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_personnelcontact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaddition',
            name='date_last_scanned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
