# Generated by Django 4.1.5 on 2023-01-18 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_productaddition_date_last_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaddition',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workcycle',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workcycle',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
