# Generated by Django 4.1.5 on 2023-01-18 08:13

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_productaddition_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent_company',
            field=models.ForeignKey(default=products.models.BrandParentCompany.get_default, on_delete=django.db.models.deletion.DO_NOTHING, related_name='upcs', to='products.brandparentcompany'),
        ),
    ]
