# Generated by Django 4.1.5 on 2023-01-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_product_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Unknown product name', max_length=255),
        ),
    ]
