# Generated by Django 4.1.5 on 2023-01-22 03:16

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_product_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent_company',
            field=models.ForeignKey(default=products.models.BrandParentCompany.get_default, on_delete=django.db.models.deletion.DO_NOTHING, related_name='upcs', to='products.brandparentcompany'),
        ),
    ]
