# Generated by Django 4.1.5 on 2023-01-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_product_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandparentcompany',
            name='expanded_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
