# Generated by Django 4.1.5 on 2023-01-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_brandparentcompany_expanded_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandparentcompany',
            name='short_name',
            field=models.CharField(default='Unknown', max_length=50, unique=True),
        ),
    ]
