# Generated by Django 4.1.5 on 2023-01-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_remove_store_store_contact_personnelcontact_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandparentcompany',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
