# Generated by Django 4.1.5 on 2023-02-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_brandparentcompany_short_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brandparentcompany',
            table='brand_parent_companies',
        ),
        migrations.AlterModelTable(
            name='fieldrepresentative',
            table='field_representatives',
        ),
        migrations.AlterModelTable(
            name='personnelcontact',
            table='personnel_contacts',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productaddition',
            table='product_additions',
        ),
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
        migrations.AlterModelTable(
            name='workcycle',
            table='work_cycles',
        ),
    ]
