# Generated by Django 4.1.5 on 2023-02-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_brandparentcompany_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
