# Generated by Django 4.1.5 on 2023-02-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_product_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
