# Generated by Django 4.1.5 on 2023-03-09 08:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('products', '0047_brandparentcompany_third_party_logo'), ('products', '0048_alter_brandparentcompany_third_party_logo'), ('products', '0049_barcodesheet'), ('products', '0050_rename_date_created_barcodesheet_datetime_created_and_more'), ('products', '0051_barcodesheet_parent_company'), ('products', '0052_alter_barcodesheet_unique_together'), ('products', '0053_product_date_added'), ('products', '0054_alter_product_date_added')]

    dependencies = [
        ('products', '0001_squashed_0046_alter_product_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandparentcompany',
            name='third_party_logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/brand_logos'),
        ),
        migrations.AlterUniqueTogether(
            name='workcycle',
            unique_together={('start_date', 'end_date')},
        ),
        migrations.CreateModel(
            name='BarcodeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_additions', models.ManyToManyField(related_name='barcode_sheets', to='products.productaddition')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_sheets', to='products.store')),
                ('work_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_sheets', to='products.workcycle')),
                ('parent_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_sheets', to='products.brandparentcompany')),
            ],
            options={
                'db_table': 'barcode_sheets',
                'unique_together': {('store', 'parent_company', 'work_cycle')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
