# Generated by Django 4.1.5 on 2023-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_squashed_0046_alter_product_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandparentcompany',
            name='third_party_logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
    ]
