# Generated by Django 4.1.5 on 2023-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_brandparentcompany_third_party_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandparentcompany',
            name='third_party_logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/brand_logos'),
        ),
    ]
