# Generated by Django 4.1.5 on 2023-02-21 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_brandparentcompany_third_party_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_additions', models.ManyToManyField(related_name='barcode_sheets', to='products.productaddition')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_sheets', to='products.store')),
                ('work_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_sheets', to='products.workcycle')),
            ],
            options={
                'db_table': 'barcode_sheets',
                'unique_together': {('store', 'work_cycle')},
            },
        ),
    ]
