# Generated by Django 4.1.5 on 2023-02-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_barcodesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcodesheet',
            old_name='date_created',
            new_name='datetime_created',
        ),
        migrations.AlterUniqueTogether(
            name='workcycle',
            unique_together={('start_date', 'end_date')},
        ),
    ]
