# Generated by Django 4.1.5 on 2023-02-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_rename_date_created_barcodesheet_datetime_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodesheet',
            name='parent_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_sheets', to='products.brandparentcompany'),
        ),
    ]
