# Generated by Django 4.1.5 on 2023-02-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_barcodesheet_parent_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barcodesheet',
            unique_together={('store', 'parent_company', 'work_cycle')},
        ),
    ]
