# Generated by Django 4.1.5 on 2023-02-24 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_alter_barcodesheet_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(default=datetime.datetime(1969, 12, 31, 19, 0)),
        ),
    ]
