# Generated by Django 4.1.5 on 2023-03-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_brandparentcompany_third_party_logo_squashed_0054_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barcodesheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='barcodesheet',
            name='upcs_hash',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='barcodesheet',
            unique_together={('store', 'parent_company', 'work_cycle', 'upcs_hash')},
        ),
    ]
