# Generated by Django 4.1.5 on 2023-03-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_alter_barcodesheet_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodesheet',
            name='upcs_hash',
            field=models.TextField(null=True),
        ),
    ]
