# Generated by Django 4.0.1 on 2023-07-12 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_barcodesheet_upcs_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='barcodesheet',
            name='product_additions',
            field=models.ManyToManyField(related_name='barcode_sheets', to='products.ProductAddition'),
        ),
        migrations.AlterField(
            model_name='brandparentcompany',
            name='short_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_guids',
            field=models.ManyToManyField(related_name='stores', to='products.StoreGUID'),
        ),
    ]
