# Generated by Django 4.0.1 on 2023-08-07 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_storeguid_store_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledProductAdditionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_product_addition_updates', to='products.workcycle')),
            ],
            options={
                'db_table': 'scheduled_product_addition_update',
            },
        ),
        migrations.AddField(
            model_name='productaddition',
            name='scheduled_updates',
            field=models.ManyToManyField(related_name='product_additions', to='products.ScheduledProductAdditionUpdate'),
        ),
    ]
