# Generated by Django 4.0.1 on 2023-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_remove_scheduledproductadditionupdate_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaddition',
            name='scheduled_updates',
        ),
        migrations.AddField(
            model_name='productaddition',
            name='date_ordered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ScheduledProductAdditionUpdate',
        ),
    ]
