# Generated by Django 4.0.1 on 2023-08-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_remove_productaddition_scheduled_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='guid',
            field=models.TextField(null=True, unique=True),
        ),
    ]
