# Generated by Django 4.0.1 on 2023-08-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_store_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='guid',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
