# Generated by Django 4.0.1 on 2023-09-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_alter_store_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcycle',
            name='cmklaunch_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workcycle',
            name='store_guid_to_store_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
