# Generated by Django 4.0.1 on 2023-09-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_workcycle_cmklaunch_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldrepresentative',
            name='repid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
