# Generated by Django 4.0.1 on 2023-09-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_fieldrepresentative_repid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workcycle',
            old_name='store_guid_to_store_info',
            new_name='cmklaunch_stores',
        ),
    ]
