# Generated by Django 4.0.1 on 2023-09-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_rename_store_guid_to_store_info_workcycle_cmklaunch_stores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldrepresentative',
            old_name='repid',
            new_name='mv_rep_id',
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='mv_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='mv_user',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
