# Generated by Django 4.0.1 on 2023-09-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_rename_repid_fieldrepresentative_mv_rep_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workcycle',
            old_name='cmklaunch_stores',
            new_name='cmklaunch_stores_data',
        ),
    ]
