# Generated by Django 4.0.1 on 2023-09-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_rename_cmklaunch_stores_workcycle_cmklaunch_stores_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcycle',
            name='cmklaunch_stores_data',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='workcycle',
            name='cmklaunch_urls',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
