# Generated by Django 4.0.1 on 2023-09-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_remove_fieldrepresentative_mv_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcycle',
            name='cmklaunch_stores_data',
        ),
        migrations.RemoveField(
            model_name='workcycle',
            name='cmklaunch_urls',
        ),
    ]
