# Generated by Django 4.0.1 on 2025-04-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_barcodesheet_upcs_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='site_id',
            field=models.IntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='guid',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
