# Generated by Django 4.0.1 on 2025-04-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_alter_store_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='site_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
