# Generated by Django 4.0.1 on 2025-05-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_alter_store_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandparentcompany',
            name='canonical_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
