# Generated by Django 4.0.1 on 2025-05-03 18:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_brandparentcompany_canonical_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandparentcompany',
            name='default_upc_prefixes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, default=list, size=None, verbose_name='UPC prefix digit(s)'),
        ),
        migrations.CreateModel(
            name='UpcCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_upc', models.CharField(db_index=True, max_length=20)),
                ('actual_upc', models.CharField(max_length=12)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upc_corrections', to='products.brandparentcompany')),
            ],
            options={
                'db_table': 'upc_corrections',
                'unique_together': {('parent_company', 'bad_upc')},
            },
        ),
    ]
