# Generated by Django 4.0.1 on 2025-05-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0082_brandparentcompany_default_upc_prefixes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='site_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
