# Generated by Django 4.0.1 on 2025-05-22 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0083_alter_store_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandparentcompany',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandparentcompany',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldrepresentative',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personnelcontact',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelcontact',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='upccorrection',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upccorrection',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workcycle',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workcycle',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PrefixMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(max_length=1)),
                ('product_name_regex', models.CharField(blank=True, default='', max_length=255)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefix_mappings', to='products.brandparentcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
