# Generated by Django 4.0.1 on 2025-07-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0084_brandparentcompany_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefixmapping',
            name='product_name_regex',
            field=models.CharField(max_length=255),
        ),
    ]
