# Generated by Django 5.2.16 on 2026-08-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0085_alter_prefixmapping_product_name_regex"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
