# Generated by Django 5.2.16 on 2026-08-08 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0086_store_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="last_seen",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
