# Generated by Django 5.2.16 on 2026-08-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_alter_store_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldrepresentative',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
