# Generated by Django 5.2.16 on 2026-08-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0089_message_messagerecipient_message_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="ref_str",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
