# Generated by Django 5.2.16 on 2026-08-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0091_pushsubscription_messagerecipientpushdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
